version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app-edad
    image: appedad:latest
    ports:
      - '8080:80' 
    tty: true
    stdin_open: true